### ISSUE TITLE
Exception Attempting to Start Any Cluster

### ISSUE THREAD

**Issue by xanderdunn** [datacratic/StarCluster#38]
I installed Starcluster with `sudo -H pip install https://github.com/datacratic/StarCluster/archive/vanilla_improvements.zip`.  

When I execute `starcluster start testcluster`, I get this exception:

```
slurm@dev:~$ starcluster start testcluster
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

2016-01-06 15:05:11,277 >>> Using default cluster template: testcluster
2016-01-06 15:05:11,277 >>> Validating cluster template settings...
2016-01-06 15:05:12,088 >>> Cluster template settings are valid
2016-01-06 15:05:12,088 >>> Starting cluster...
2016-01-06 15:05:12,088 >>> Launching a 2-node cluster...
2016-01-06 15:05:12,088 >>> Launching master node (ami: ami-73968e12, type: c4.large)...
2016-01-06 15:05:12,130 >>> Creating security group @sc-testcluster...
2016-01-06 15:05:13,375 >>> Creating placement group @sc-testcluster...
Reservation:r-5e0a8e9b
2016-01-06 15:05:14,350 >>> Launching node001 (ami: ami-73968e12, type: c4.large)
SpotInstanceRequest:sir-037b307h
2016-01-06 15:05:14,816 >>> Waiting for spot requests to propagate...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:05:15,372 >>> Waiting for instances to propagate...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:05:15,601 >>> Waiting for cluster to come up... (updating every 30s)
2016-01-06 15:05:15,739 >>> Waiting for open spot requests to become active...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:07:22,970 >>> Waiting for instances to propagate...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:07:23,151 >>> Waiting for all nodes to be in a 'running' state...
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:07:23,976 >>> Waiting for SSH to come up on all nodes...
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:07:41,117 >>> Waiting for cluster to come up took 2.425 mins
2016-01-06 15:07:41,117 >>> The master node is ec2-52-33-69-62.us-west-2.compute.amazonaws.com
2016-01-06 15:07:41,118 >>> Configuring cluster...
2016-01-06 15:07:41,225 >>> Running plugin starcluster.clustersetup.DefaultClusterSetup
2016-01-06 15:07:41,225 >>> Configuring hostnames...
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:07:42,399 >>> Creating cluster user: sgeadmin (uid: 1001, gid: 1001)
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:08:08,433 >>> Configuring scratch space for user(s): sgeadmin
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:08:16,445 >>> Configuring /etc/hosts on each node
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:08:17,448 >>> Starting NFS server on master
/tmp/exports_WhJ3KK 100% |||||||||||||||||||||||||||| Time: 00:00:00 295.63 K/s
exports_KU4uKi 100% ||||||||||||||||||||||||||||||||| Time: 00:00:00   2.12 M/s
2016-01-06 15:08:18,421 >>> Configuring NFS exports path(s):
/home
2016-01-06 15:08:18,505 >>> Mounting all NFS export path(s) on 1 worker node(s)
/tmp/fstab__mAKGc 100% |||||||||||||||||||||||||||||| Time: 00:00:00  74.34 K/s
fstab_yCLP_c 100% ||||||||||||||||||||||||||||||||||| Time: 00:00:00 642.73 K/s
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:08:19,507 >>> Setting up NFS took 0.034 mins
2016-01-06 15:08:19,508 >>> Configuring passwordless ssh for root
/tmp/id_rsa_tz1NyL 100% ||||||||||||||||||||||||||||| Time: 00:00:00   1.28 M/s
id_rsa_tz1NyL 100% |||||||||||||||||||||||||||||||||| Time: 00:00:00  10.40 M/s
/tmp/id_rsa.pub_xfXcDN 100% ||||||||||||||||||||||||| Time: 00:00:00 293.20 K/s
id_rsa.pub_xfXcDN 100% |||||||||||||||||||||||||||||| Time: 00:00:00   2.81 M/s
/tmp/authorized_keys_KWbGno 100% |||||||||||||||||||| Time: 00:00:00   1.34 M/s
authorized_keys_KWbGno 100% ||||||||||||||||||||||||| Time: 00:00:00  10.39 M/s
/tmp/known_hosts_J8fy5p 100% |||||||||||||||||||||||| Time: 00:00:00   2.60 M/s
known_hosts_J8fy5p 100% ||||||||||||||||||||||||||||| Time: 00:00:00  18.56 M/s
2016-01-06 15:08:20,955 >>> Configuring passwordless ssh for sgeadmin
2016-01-06 15:08:21,683 >>> Running plugin sge
2016-01-06 15:08:21,685 >>> Configuring SGE...
/tmp/exports_k1OqZz 100% |||||||||||||||||||||||||||| Time: 00:00:00 340.78 K/s
exports_58i1V0 100% ||||||||||||||||||||||||||||||||| Time: 00:00:00   2.63 M/s
2016-01-06 15:08:36,646 >>> Configuring NFS exports path(s):
/opt/sge6
2016-01-06 15:08:36,729 >>> Mounting all NFS export path(s) on 1 worker node(s)
/tmp/fstab_TWIEB8 100% |||||||||||||||||||||||||||||| Time: 00:00:00 105.87 K/s
fstab_LPjjkM 100% ||||||||||||||||||||||||||||||||||| Time: 00:00:00 938.82 K/s
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:08:37,733 >>> Setting up NFS took 0.021 mins
2016-01-06 15:08:37,739 >>> Installing Sun Grid Engine...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
2016-01-06 15:09:10,840 !!! ERROR - -------threadpool exc start---------
2016-01-06 15:09:10,841 !!! ERROR - tb_msg:
2016-01-06 15:09:10,842 !!! ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/starcluster/threadpool.py", line 48, in run
    job.run()
  File "/usr/local/lib/python2.7/dist-packages/starcluster/threadpool.py", line 81, in run
    r = self.method(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/plugins/sge.py", line 67, in _add_to_sge
    self._inst_sge(node, exec_host=True)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/plugins/sge.py", line 102, in _inst_sge
    self._setup_sge_profile(node)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/plugins/sge.py", line 60, in _setup_sge_profile
    arch = node.ssh.execute(self._sge_path("util/arch"))[0]
  File "/usr/local/lib/python2.7/dist-packages/starcluster/sshutils.py", line 579, in execute
    only_printable=only_printable)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/sshutils.py", line 523, in _get_output
    output = stdout.readlines() + stderr.readlines()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 285, in readlines
    line = self.readline()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 235, in readline
    new_data = self._read(n)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 1217, in _read
    return self.channel.recv(size)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 598, in recv
    raise socket.timeout()
timeout

2016-01-06 15:09:10,842 !!! ERROR - e:
2016-01-06 15:09:10,842 !!! ERROR -
2016-01-06 15:09:10,842 !!! ERROR - jid:
2016-01-06 15:09:10,842 !!! ERROR - node001
2016-01-06 15:09:10,842 !!! ERROR - -------threadpool exc end-----------
2016-01-06 15:09:10,843 !!! ERROR - Error occured while running plugin 'sge':
2016-01-06 15:09:10,843 !!! ERROR - error occurred in job (id=node001):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/starcluster/threadpool.py", line 48, in run
    job.run()
  File "/usr/local/lib/python2.7/dist-packages/starcluster/threadpool.py", line 81, in run
    r = self.method(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/plugins/sge.py", line 67, in _add_to_sge
    self._inst_sge(node, exec_host=True)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/plugins/sge.py", line 102, in _inst_sge
    self._setup_sge_profile(node)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/plugins/sge.py", line 60, in _setup_sge_profile
    arch = node.ssh.execute(self._sge_path("util/arch"))[0]
  File "/usr/local/lib/python2.7/dist-packages/starcluster/sshutils.py", line 579, in execute
    only_printable=only_printable)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/sshutils.py", line 523, in _get_output
    output = stdout.readlines() + stderr.readlines()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 285, in readlines
    line = self.readline()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/file.py", line 235, in readline
    new_data = self._read(n)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 1217, in _read
    return self.channel.recv(size)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 598, in recv
    raise socket.timeout()
timeout


2016-01-06 15:09:10,901 !!! ERROR - Oops! Looks like you've found a bug in StarCluster
2016-01-06 15:09:10,901 !!! ERROR - Crash report written to: /home/slurm/.starcluster/logs/crash-report-12291.txt
2016-01-06 15:09:10,901 !!! ERROR - Please remove any sensitive data from the crash report
2016-01-06 15:09:10,901 !!! ERROR - and submit it to starcluster@mit.edu
```

The exact same config works fine with latest from `sudo -H pip install https://github.com/jtriley/StarCluster/archive/develop.zip`.  

I tried commenting out as many things as I could in my config.  It's left with just the basics: AMI name and password, instance type, spot price, region, key, etc.  Same error.

**Comment by FinchPowers** [comment]
Intriguing. I'll try to reproduce it and come back to you.

**Comment by FinchPowers** [comment]
I cannot use the AMI you used in your report and hence cannot reproduce your issue.
The obvious thing I see is an SSH timeout issue, but I can't tell anything more than that.
I've got reports of the timeout being too low for certain type of instances. You could try to raise it to a few minutes and retry.

**Comment by xanderdunn** [comment]
Yes, the AMI is private.  Is the SSH timeout shorter on your branch?  The same config works fine using jtriley/StarCluster

**Comment by xanderdunn** [comment]
Also, where can I change that timeout?  Thanks!

**Comment by FinchPowers** [comment]
https://github.com/datacratic/StarCluster/blob/vanilla_improvements/starcluster/sshutils.py#L66

**Comment by FinchPowers** [comment]
I may not have given you the right line but this is the right file. There are various timeouts in it.

**Comment by xanderdunn** [comment]
Thanks.  It's identical to the upstream: https://github.com/jtriley/StarCluster/blob/develop/starcluster/sshutils.py#L65

I can give it a try, though.

**Comment by FinchPowers** [comment]
https://github.com/datacratic/StarCluster/blame/vanilla_improvements/starcluster/sshutils.py#L207
^^ This line a an addition from vanilla improvements. It may be the cause of the timeouts. Looking at it I realize lot of timeouts enforcement have been added. The core version may never timeout at all in some cases.

**Comment by xanderdunn** [comment]
That was it.  I simply changed the timeout to 300 and it worked.  Perhaps increase the default timeout?

**Comment by FinchPowers** [comment]
Yeah sounds fair.

**Comment by FinchPowers** [comment]
https://github.com/datacratic/StarCluster/pull/39
