### ISSUE TITLE
Unhandled exception when terminating a cluster

### ISSUE THREAD

**Issue by erikedlund** [datacratic/StarCluster#45]
I hit the following exception when trying to forcefully terminate a cluster:

2016-02-05 17:10:27,058 !!! ERROR - Unhandled exception occured
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cli.py", line 275, in main
    sc.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/terminate.py", line 101, in execute
    self.terminate(cluster_name, force=self.opts.force)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/terminate.py", line 85, in terminate
    self._terminate_manually(cl)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/terminate.py", line 76, in _terminate_manually
    cl.terminate_cluster(force=True)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 1876, in terminate_cluster
    self.run_plugins(method_name="on_shutdown", reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 2000, in run_plugins
    plugs += (plugins or self.plugins)[:]
TypeError: 'NoneType' object has no attribute '__getitem__'
2016-02-05 17:10:27,078 !!! ERROR - Oops! Looks like you've found a bug in StarCluster

Is it just that the plugins or self.plugins objects are null at that time? If so, can they be ignored?

**Comment by FinchPowers** [comment]
They can and the cluster will shut down, but if you have some stop/remove node logic in your plugins that you rely on, it won't get called.

Are you using plugins? If you are not, then this is likely the good fix.

**Comment by erikedlund** [comment]
Thanks for the quick response. I'm using some custom plugins I wrote before switching to this fork, and I notice that I haven't implemented the on_remove_node method for any of them. Would you expect that to cause a problem?

**Comment by FinchPowers** [comment]
No I don't. If you can track it down I will welcome the fix. :)
