### ISSUE TITLE
Error creating EBS volume on existing host with VPC

### ISSUE THREAD

**Issue by johncolby** [datacratic/StarCluster#59]
Small bug. In starcluster/volume.py need to update "subnet_id" to "subnet_ids". Then it works fine. Thanks. -John

```
>>starcluster createvolume -H i-fca37d6b --name=HCP 10 us-west-1c
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

2016-09-19 15:38:04,470 !!! ERROR - Unhandled exception occured
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/cli.py", line 275, in main
    sc.execute(args)
  File "/Library/Python/2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/commands/createvolume.py", line 144, in execute
    vc = volume.VolumeCreator(self.ec2, **kwargs)
  File "/Library/Python/2.7/site-packages/StarCluster-0.9999-py2.7.egg/starcluster/volume.py", line 66, in __init__
    node_instance_type=self._instance_type, force_spot_master=True)
TypeError: __init__() got an unexpected keyword argument 'subnet_id'
```

**Comment by FinchPowers** [comment]
Thanks!
