### ISSUE TITLE
Permission denied error when using EFS plugin

### ISSUE THREAD

**Issue by alexbw** [datacratic/StarCluster#66]
Hello all, the EFS plugin is giving me a bit of trouble, requiring manual intervention on startup on my part.

I get the following error:

```
2017-02-08 19:11:24,354 !!! ERROR - Error occured while running plugin 'efs':
2017-02-08 19:11:24,355 !!! ERROR - Unhandled exception occured
Traceback (most recent call last):
  File "/Users/Alex/Code/StarCluster/starcluster/cli.py", line 275, in main
    sc.execute(args)
  File "/Users/Alex/Code/StarCluster/starcluster/commands/start.py", line 283, in execute
    save_config_on_master=self.opts.config_on_master)
  File "/Users/Alex/Code/StarCluster/starcluster/cluster.py", line 1942, in start
    save_config_on_master=save_config_on_master)
  File "<decorator-gen-18>", line 2, in _start
  File "/Users/Alex/Code/StarCluster/starcluster/utils.py", line 112, in wrap_f
    res = func(*arg, **kargs)
  File "/Users/Alex/Code/StarCluster/starcluster/cluster.py", line 1966, in _start
    self.setup_cluster(save_config_on_master)
  File "/Users/Alex/Code/StarCluster/starcluster/cluster.py", line 1975, in setup_cluster
    self._setup_cluster(save_config_on_master)
  File "<decorator-gen-20>", line 2, in _setup_cluster
  File "/Users/Alex/Code/StarCluster/starcluster/utils.py", line 112, in wrap_f
    res = func(*arg, **kargs)
  File "/Users/Alex/Code/StarCluster/starcluster/cluster.py", line 1989, in _setup_cluster
    self.run_plugins()
  File "/Users/Alex/Code/StarCluster/starcluster/cluster.py", line 2010, in run_plugins
    nodes=nodes)
  File "/Users/Alex/Code/StarCluster/starcluster/cluster.py", line 2038, in run_plugin
    func(*args)
  File "/Users/Alex/Code/StarCluster/starcluster/plugins/efs.py", line 53, in run
    self._install_efs_on_node(node)
  File "/Users/Alex/Code/StarCluster/starcluster/plugins/efs.py", line 141, in _install_efs_on_node
    node.ssh.makedirs(self.mount_point, mode=0777)
  File "/Users/Alex/Code/StarCluster/starcluster/sshutils.py", line 261, in makedirs
    self.mkdir(path, mode)
  File "/Users/Alex/Code/StarCluster/starcluster/sshutils.py", line 272, in mkdir
    return self.sftp.mkdir(path, mode)
  File "/Users/Alex/anaconda/envs/py27/lib/python2.7/site-packages/paramiko/sftp_client.py", line 380, in mkdir
    self._request(CMD_MKDIR, path, attr)
  File "/Users/Alex/anaconda/envs/py27/lib/python2.7/site-packages/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/Users/Alex/anaconda/envs/py27/lib/python2.7/site-packages/paramiko/sftp_client.py", line 781, in _read_response
    self._convert_status(msg)
  File "/Users/Alex/anaconda/envs/py27/lib/python2.7/site-packages/paramiko/sftp_client.py", line 809, in _convert_status
    raise IOError(errno.EACCES, text)
IOError: [Errno 13] Permission denied
```

However, when I log in as root and run:
```
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 172.30.1.70:/   /data/efs
```
that always works just fine. Is there some setup or configuration issue on my end with my EFS drive?

Thanks again for keeping this project alive.

**Comment by jraby** [comment]
From the stack trace, it seems to be failing either:
  - when connecting to the node via sftp (to create the mount point directory)
  - or after the sftp connection is made, when trying to create the mount point.

In any case, it has not reached the 'nfs mount' code yet, it fails before that.

I would suggest to investigate if the sftp connection is properly brought up, and if that's fine, why would  `self.mount_point` fail to be created?  (read only fs? connected as non-root?)

**Comment by vasisht** [comment]
@alexbw see #52 Are you running any plugins before running efs? Does this happen when you run efs as the first plugin?

**Comment by alexbw** [comment]
The issue was the mount directory didn't exist at the time the EFS plugin was run. The only way I can see improving this is to provide a better error message — otherwise, it's all user error.
